choco install -y vscode
Update-SessionEnvironment
#vs code extensions
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension msjsdiag.debugger-for-edge
code --install-extension yzhang.markdown-all-in-one
code --install-extension mdickin.markdown-shortcuts
code --install-extension aaron-bond.better-comments
code --install-extension abusaidm.html-snippets
code --install-extension Angular.ng-template
code --install-extension axetroy.vscode-changelog-generator
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension cyrilletuzi.angular-schematics
code --install-extension danwahlin.angular2-snippets
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension ego-digital.vscode-powertools
ecode --install-extension sbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension hardikpthv.AngularMaterial
code --install-extension jchannon.csharpextensions
code --install-extension johnpapa.angular-essentials
code --install-extension johnpapa.Angular2
code --install-extension Leopotam.csharpfixformat
code --install-extension code --install-extension Mikael.Angular-BeastCode
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension ms-vsts.team
code --install-extension natewallace.angular2-inline
code --install-extension nrwl.angular-console
code --install-extension PKief.material-icon-theme
code --install-extension rbbit.typescript-hero
code --install-extension steoates.autoimport
code --install-extension stringham.move-ts
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wwm.better-align
code --install-extension Zignd.html-css-class-completion